parameters:
  model_type:
    values:
      - SiLIF
  pdrop:
    values:
      - 0.5
  lr:
    values:
      - 0.001
  batch_size:
    values:
      - 32
  scheduler_patience:
    values:
      - 5
  dataset_name:
    values:
      - sc
  data_folder:
    values:
      - //Local/datasets/GSC/
  log_tofile:
    values:
      - true
