parameters:
  model_type:
    values:
      - adLIF
  pdrop:
    values:
      - 0.25
  lr:
    values:
      - 0.05
  batch_size:
    values:
      - 128
  nb_steps:
    values:
      - 250
  max_time:
    values:
      - 1
  spatial_bin:
    values:
      - 5
  dataset_name:
    values:
      - shd
  data_folder:
    values:
      - //Local/datasets/SHD/
  only_createsweep:
    values:
      - true
  log_tofile:
    values:
      - true
