parameters:
  model_type:
    values:
      - SiLIF
  pdrop:
    values:
      - 0.5
  lr:
    values:
      - 0.01
  batch_size:
    values:
      - 256
  nb_steps:
    values:
      - 300
  max_time:
    values:
      - 1.2
  spatial_bin:
    values:
      - 5
  dataset_name:
    values:
      - ssc
  data_folder:
    values:
      - //Local/datasets/ssc/
  log_tofile:
    values:
      - true
  load_exp_folder:
    values:
      - SSM-inspired-LIF/reference_models/ref_SSC_SiLIF/
