parameters:
  model_type:
    values:
      - CSiLIF
  dt_max:
    values:
      - 5
  pdrop:
    values:
      - 0.5
  lr:
    values:
      - 0.005
  batch_size:
    values:
      - 256
  nb_steps:
    values:
      - 100
  max_time:
    values:
      - 1.0
  spatial_bin:
    values:
      - 5
  dataset_name:
    values:
      - ssc
  data_folder:
    values:
      - //Local/datasets/ssc/
  log_tofile:
    values:
      - true
